# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sit', models.IntegerField(choices=[(1, '입석'), (2, '착석')])),
                ('detail', models.IntegerField(choices=[(1, '콩나물 시루다'), (2, '자리는 없다'), (3, '자리가 남아 있다')])),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('weather', models.CharField(max_length=20)),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=250)),
                ('stacked_data', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='subway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Subway'),
        ),
        migrations.AddField(
            model_name='data',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Schedule'),
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.User'),
        ),
    ]
