# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20160930_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
