# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20160930_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exist_user',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_station',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='stacked_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.CharField(max_length=50),
        ),
    ]
