# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20161006_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recent_station',
        ),
    ]
